"""alter user

Revision ID: 1fcbe0c86a27
Revises: 4577d4a0c356
Create Date: 2023-08-08 08:51:01.404287

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1fcbe0c86a27"
down_revision: Union[str, None] = "4577d4a0c356"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
