"""alter task_list

Revision ID: 2873b4c4a6af
Revises: fa3e6915373a
Create Date: 2023-08-11 13:51:15.546982

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2873b4c4a6af"
down_revision: Union[str, None] = "fa3e6915373a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_lists",
        "active_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_lists", "active_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
